export const {
  REACT_APP_DEV_API: DEV_API,
  REACT_APP_PROD_API: PROD_API,
  REACT_APP_MODE: MODE,
  REACT_APP_SERVER_DEV_API: SERVER_DEV_API,
  REACT_APP_SERVER_PROD_API: SERVER_PROD_API,
} = process.env;
